package fr.demonis.javaproject.Utils;

public enum Specialities {
    GENERAL,ALLERGISTS,IMMUNOLOGISTS,ANESTHESIOLOGISTS,CARDIOLOGISTS,COLON_AND_RECTAL_SURGEONS,CRITICAL_CARE,MEDICINE_SPECIALISTS,DERMATOLOGISTS,ENDOCRINOLOGISTS,EMERGENCY_MEDICINE_SPECIALISTS,FAMILY_PHYSICIANS,GASTROENTEROLOGISTS,GERIATRIC_MEDICINE_SPECIALISTS

}
